### ISSUE TITLE
bug: Error while initializing app error: relation "connectors" does not exist

### ISSUE THREAD

**Issue by bulolo** [logto-io/logto#1580]
```
# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:prerelease
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@postgres:5432
      - ENDPOINT
  postgres:
    image: postgres:14-alpine
    user: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```

```
> start


> cd packages/core && NODE_ENV=production node . --from-root




Error while initializing app error: relation "connectors" does not exist


    at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/parser.js:287:98)


    at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/parser.js:126:29)


    at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/parser.js:39:38)


    at Socket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/index.js:11:42)


    at Socket.emit (node:events:527:28)


    at addChunk (node:internal/streams/readable:315:12)


    at readableAddChunk (node:internal/streams/readable:289:9)


    at Socket.Readable.push (node:internal/streams/readable:228:10)


    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
```

**Comment by gao-sun** [comment]
closed until the content meets our template

**Comment by simeng-li** [comment]
@bulolo please follow our issue template with some necessary context. So we can better help.

**Comment by CNLHC** [comment]
I just encountered the same issue. 
A temporary solution is to seed your database in an interactive console before using `ALL_YES=1`
