### ISSUE TITLE
bug: Gitpod environment missing env variable

### ISSUE THREAD

**Issue by lukashass** [logto-io/logto#2103]
### Describe the bug

When launching Logto in Gitpod the startup fails:

```
@logto/core: [error] No Postgres DSN (DB_URL) found in env variables.
@logto/core:   Either provide it in your env, or add it to the .env file in the Logto project root.
@logto/core:   If you want to set up a new Logto database, run npm run cli db seed before setting env DB_URL.
@logto/core:   Visit https://docs.logto.io/docs/references/core/configuration for more info about setting up env.
@logto/core: Error while initializing app Error: env variable DB_URL not found
@logto/core:     at assertEnv (/workspace/logto/node_modules/.pnpm/@silverhand+essentials@1.2.1/node_modules/@silverhand/essentials/lib/utilities/env.js:24:33)
@logto/core:     at createPoolByEnv (/workspace/logto/packages/core/build/env-set/create-pool-by-env.js:18:56)
@logto/core:     at Object.load (/workspace/logto/packages/core/build/env-set/index.js:83:59)
@logto/core:     at async /workspace/logto/packages/core/build/index.js:21:9
```

### Expected behavior

Startup without error.

### How to reproduce?

Open Gitpod.

### Context

Gitpod

**Comment by gao-sun** [comment]
@lukashass really appreciate this. besides the fix #2104, we'd like to do two things if possible:

- add gitpod prebuild/preinstall
- add gitpod checking for PRs/master branch
- using `prerelease` image instead of the latest code for public preview
