### ISSUE TITLE
bug: Can not init logto

### ISSUE THREAD

**Issue by datnq** [logto-io/logto#2603]
### Describe the bug
Run `npm init @logto` and see error:

```
.npm/_npx/75761ac6b328cdec/node_modules/@logto/connector-kit/lib/types.js:4
const language_kit_1 = require("@logto/language-kit");
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/connector-kit/node_modules/@logto/language-kit/lib/index.js from /home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/connector-kit/lib/types.js not supported.
Instead change the require of index.js in /home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/connector-kit/lib/types.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/connector-kit/lib/types.js:4:24)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/connector-kit/lib/index.js:18:20)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/schemas/lib/types/connector.js:4:23)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/schemas/lib/types/index.js:17:14)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/schemas/lib/index.js:32:14)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/lib/commands/database/seed/index.js:9:19)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/lib/commands/install/utils.js:43:16)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/lib/commands/connector/utils.js:21:17)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/lib/commands/connector/add.js:4:17)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/lib/commands/connector/index.js:7:31)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/lib/index.js:10:37)
    at Object.<anonymous> (/home/joey/.npm/_npx/75761ac6b328cdec/node_modules/@logto/cli/bin/logto:2:1) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code 1
npm ERR! path /home/joey/logto
npm ERR! command failed
npm ERR! command sh -c logto-create

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joey/.npm/_logs/2022-12-06T19_15_53_294Z-debug-0.log
```

### Expected behavior
Logto application created

### How to reproduce?
`npm init @logto`

### Context

OS: 

Environment: 
wsl2 (Ubuntu)

Logto version: 
`@logto/create@1.0.0-beta.16`

Node version:

Postgres version: 

Command of starting Logto:

**Comment by charIeszhao** [comment]
Hi @datnq, thank you for reporting. We are able to reproduce this issue and investigating the root cause right now. Will try to fix it ASAP.

**Comment by gao-sun** [comment]
@datnq would you like to [clean the cache](https://stackoverflow.com/questions/63510325/how-can-i-clear-the-central-cache-for-npx) of npx and try again with `npm init @logto@latest`? lmk if it works

**Comment by datnq** [comment]
Had a quick run, it works @gao-sun

Great thanks,
