### ISSUE TITLE
bug: Cannot enable Machine-to-Machine Admin Access

### ISSUE THREAD

**Issue by feropeterko** [logto-io/logto#3474]
### Describe the bug
Application crashed after switch "Enable admin access" was enabled.

### Expected behavior
Enable admin access

### How to reproduce?
Create Machine-to-Machine application and tick "Enable admin access" switch

### Context

Environment: docker image with "prod" tag (digest: 9b47877399a6)

### Error message

```
error: column "applications_roles" of relation "applications_roles" does not exist
at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
at Socket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
2at Socket.emit (node:events:513:28)
at Socket.emit (node:domain:489:12)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
```

**Comment by gao-sun** [comment]
please use `prerelease` for the latest release of logto as `prod` is not a stable tag. will remove the tag soon.

**Comment by gao-sun** [comment]
closing since this tag is not for release. feel free to create a new issue if the error persists in `prerelease` tag
