### ISSUE TITLE
bug: SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by liushunshun** [logto-io/logto#3475]
[root@VM-100-5-centos ~]# logto --help
/usr/local/lib/node_modules/@logto/cli/bin/logto.js:2
import '../lib/index.js';
       ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by gao-sun** [comment]
Node@^18 is required to use CLI

**Comment by gao-sun** [comment]
your node version is too old
