### ISSUE TITLE
bug: ERROR:  column "applications_roles" of relation "applications_roles" does not exist

### ISSUE THREAD

**Issue by wernerm** [logto-io/logto#3646]
### Describe the bug

Edited an existing Machine to Machine (M2M) Application and enabled the "Enable admin access" checkbox. when hitting "Save", the error is thrown.

### Expected behavior

I expected the change(s) to be applied (saved) and to be returned to the Applications list.

### How to reproduce?

1. Install a new Logto docker instance using instance, using:
`curl -fsSL https://raw.githubusercontent.com/logto-io/logto/HEAD/docker-compose.yml | TAG=prerelease docker compose -p logto -f - up`
3. Create a new M2M Application. Do not enable the "Enable admin access" checkbox. Save the Application.
4. Edit the existing, newly created M2M Application. Enable the "Enable admin access" checkbox and hit "Save" to apply the changes. The error is thrown.

### Context

OS: Ubuntu 22.04.2 LTS
Environment: Docker Compose
Logto version: Latest (How do I check the version?) 
Node version: v18.15.0 (as per container)
Postgres version: PostgreSQL 14.7 (as per container)
Command of starting Logto: `curl -fsSL https://raw.githubusercontent.com/logto-io/logto/HEAD/docker-compose.yml | TAG=prerelease docker compose -p logto -f - up`

### Screenshots

https://user-images.githubusercontent.com/411270/228920100-4bee8c5c-666d-437d-9c76-4f6989f6e993.mp4

### Log Output

```sh
logto-app-1       |   <-- OPTIONS /api/applications/o2geDwoI3cb6EML5pNM4K
logto-app-1       |   --> OPTIONS /api/applications/o2geDwoI3cb6EML5pNM4K 204 1ms 
logto-app-1       |   <-- PATCH /api/applications/o2geDwoI3cb6EML5pNM4K
logto-postgres-1  | 2023-03-30 17:39:03.865 UTC [626] ERROR:  column "applications_roles" of relation "applications_roles" does not exist at character 35
logto-postgres-1  | 2023-03-30 17:39:03.865 UTC [626] STATEMENT:  insert into "applications_roles" ("applications_roles"."id", "applications_roles"."application_id", "applications_roles"."role_id") values ($1, $2, $3)
logto-app-1       | error: column "applications_roles" of relation "applications_roles" does not exist
logto-app-1       |     at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
logto-app-1       |     at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
logto-app-1       |     at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
logto-app-1       |     at Socket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
logto-app-1       |     at Socket.emit (node:events:513:28)
logto-app-1       |     at Socket.emit (node:domain:489:12)
logto-app-1       |     at addChunk (node:internal/streams/readable:324:12)
logto-app-1       |     at readableAddChunk (node:internal/streams/readable:297:9)
logto-app-1       |     at Readable.push (node:internal/streams/readable:234:10)
logto-app-1       |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
logto-app-1       |   length: 149,
logto-app-1       |   severity: 'ERROR',
logto-app-1       |   code: '42703',
logto-app-1       |   detail: undefined,
logto-app-1       |   hint: undefined,
logto-app-1       |   position: '35',
logto-app-1       |   internalPosition: undefined,
logto-app-1       |   internalQuery: undefined,
logto-app-1       |   where: undefined,
logto-app-1       |   schema: undefined,
logto-app-1       |   table: undefined,
logto-app-1       |   column: undefined,
logto-app-1       |   dataType: undefined,
logto-app-1       |   constraint: undefined,
logto-app-1       |   file: 'parse_target.c',
logto-app-1       |   line: '1061',
logto-app-1       |   routine: 'checkInsertTargets',
logto-app-1       |   notices: [],
logto-app-1       |   headers: {
logto-app-1       |     'Access-Control-Allow-Origin': 'http://localhost:3002',
logto-app-1       |     'Access-Control-Expose-Headers': '*',
logto-app-1       |     vary: 'Origin'
logto-app-1       |   }
logto-app-1       | }
logto-app-1       |   --> PATCH /api/applications/o2geDwoI3cb6EML5pNM4K 500 73ms 36b
```

**Comment by gao-sun** [comment]
would you like to use the latest Logto image and try again? note `TAG=prerelease` should be removed

**Comment by wernerm** [comment]
Thank you, that seems to have resolved the issue
