### ISSUE TITLE
bug: Client Object does not work properly

### ISSUE THREAD

**Issue by afonso-pereira** [logto-io/logto#4677]
Following the Python setup guide, and forcing the flask code to fetch user details by changing the value in the condition:
![image](https://github.com/logto-io/logto/assets/54318711/865a9731-59ea-43a1-9a02-845bd02985f3)
The following error is obtained:

Traceback (most recent call last):
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/afonso/PyCharm/projectname/project/app.py", line 99, in home
    client.getIdTokenClaims().model_dump_json(exclude_unset=True)+ "<br>"
  File "/home/afonso/.virtualenvs/venv_name/lib/python3.11/site-packages/logto/LogtoClient.py", line 438, in getIdTokenClaims
    raise LogtoException("ID Token not found")
logto.LogtoException.LogtoException: ID Token not found

Everything else related to logto is configured as is in the setup guide provided.
Python 3.11

**Comment by afonso-pereira** [comment]
This happened while logged in into the app.

**Comment by afonso-pereira** [comment]
mentioned in https://github.com/logto-io/logto/issues/4674
Closing this issue, as I believe the root cause is the same.

**Comment by afonso-pereira** [comment]
[Fixed by following this code](https://github.com/logto-io/python/blob/master/samples/flask.py)

**Comment by gao-sun** [comment]
it seems this error is expected when user is not authenticated
