### ISSUE TITLE
feature request: expose error_detail from oidc-provider

### ISSUE THREAD

**Issue by JakeHedman** [logto-io/logto#5070]
### What problem did you meet?
Trying to debug an InvalidGrant error shows a stack like this in the audit log, but the `error_detail` field from oidc-provider is omitted making it a nightmare to debug.
```
InvalidGrant: invalid_grant
    at file:///etc/logto/packages/core/build/oidc/grants/refresh-token.js:72:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callTokenHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:70:7)
    at async allowedGrantTypeCheck (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:53:7)
    at async supportedGrantTypeCheck (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:45:7)
    at async stripGrantIrrelevantParams (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:33:7)
    at async auth (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:257:9)
    at async loadClient (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:152:9)
    at async setWWWAuthenticateHeader (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:43:11)
    at async selectiveBody (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)
    at async noCache (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)
    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)
    at async ensureSessionSave (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)
    at async contextEnsureOidc (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)
    at async file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:222:5
    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)
```

### Describe what you'd like Logto to have
Expose more data from oidc-provider so we can have an idea of what's going on when it errors out.

**Comment by charIeszhao** [comment]
I think the error details are included in the audit log, as I can see them in a previously reported ticket: https://github.com/logto-io/js/issues/503

**Comment by JakeHedman** [comment]
> I think the error details are included in the audit log, as I can see them in a previously reported ticket: [logto-io/js#503](https://github.com/logto-io/js/issues/503)

No, that's just `error_description` and not `error_details`.

All `InvalidGrant` errors have [the same `error_description`](https://github.com/panva/node-oidc-provider/blob/a450345c34ebf3c489c36c689727a567961cbcfa/lib/helpers/errors.js#L85), but there are [26 different `error_details`](https://github.com/search?q=repo%3Apanva/node-oidc-provider%20InvalidGrant&type=code) which the audit log does not include, making it hard to figure out where the error originated from and what went wrong.

**Comment by JakeHedman** [comment]
> This issue is stale because it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Bump

**Comment by charIeszhao** [comment]
> > I think the error details are included in the audit log, as I can see them in a previously reported ticket: [logto-io/js#503](https://github.com/logto-io/js/issues/503)
> 
> No, that's just `error_description` and not `error_details`.
> 
> All `InvalidGrant` errors have [the same `error_description`](https://github.com/panva/node-oidc-provider/blob/a450345c34ebf3c489c36c689727a567961cbcfa/lib/helpers/errors.js#L85), but there are [26 different `error_details`](https://github.com/search?q=repo%3Apanva/node-oidc-provider%20InvalidGrant&type=code) which the audit log does not include, making it hard to figure out where the error originated from and what went wrong.

Sorry for the delay of response. 

But if you take a closer look at the ticket I mentioned earlier, there are both `error_description` and `error_detail` in their audit logs. For example:
<img width="909" alt="image" src="https://github.com/logto-io/logto/assets/12833674/9b6f190e-772b-4bb2-a4d3-60955700c4c4">

**Comment by JakeHedman** [comment]
> > > I think the error details are included in the audit log, as I can see them in a previously reported ticket: [logto-io/js#503](https://github.com/logto-io/js/issues/503)
> > 
> > 
> > No, that's just `error_description` and not `error_details`.
> > All `InvalidGrant` errors have [the same `error_description`](https://github.com/panva/node-oidc-provider/blob/a450345c34ebf3c489c36c689727a567961cbcfa/lib/helpers/errors.js#L85), but there are [26 different `error_details`](https://github.com/search?q=repo%3Apanva/node-oidc-provider%20InvalidGrant&type=code) which the audit log does not include, making it hard to figure out where the error originated from and what went wrong.
> 
> Sorry for the delay of response.
> 
> But if you take a closer look at the ticket I mentioned earlier, there are both `error_description` and `error_detail` in their audit logs. For example: <img alt="image" width="909" src="https://private-user-images.githubusercontent.com/12833674/294826041-9b6f190e-772b-4bb2-a4d3-60955700c4c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDYzMDMsIm5iZiI6MTcwNTA0NjAwMywicGF0aCI6Ii8xMjgzMzY3NC8yOTQ4MjYwNDEtOWI2ZjE5MGUtNzcyYi00YmIyLWE0ZDMtNjA5NTU3MDBjNGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA3NTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NGE3ZGMwYzEyMjgwZWY1ZTYwNjA5YWRmZDg3MTMyMTJhYzhmZjYwMjBkNDk5OWI4ZWExOGQyMzUwYjQxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kjDOxbTZ7Dn5ICwGWqPECiF6S42Xfcqx1V7d-U_5MFQ">

Yeah you're right, not sure how I missed it. Sorry about that!

Better formatting for the `"error"` field would be convenient.
