### ISSUE TITLE
bug: Database name is required in URL

### ISSUE THREAD

**Issue by vinumweb** [logto-io/logto#5586]
### Describe the bug
When starting the logto with docker compose I get an error saying ```fatal Error: Database name is required in URL
    at createPoolFromConfig (file:///etc/logto/packages/cli/lib/database.js:16:48)
    at async createPoolAndDatabaseIfNeeded (file:///etc/logto/packages/cli/lib/database.js:29:16)
    at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:61:22)```

### Expected behavior
Logto seeding the db like normal

### How to reproduce?
Using the docker compose in Easypanel, and setting the start command.

### Context
I'm using Easypanel (it's like portainer)
- [ ] Logto Cloud
- [X] Self-hosted, Logto version = latest 
  - [X] Container (Docker image)
  - [ ] Raw Node.js

**Comment by wangsijie** [comment]
What is your `DB_URL` in the compose file?

**Comment by wangsijie** [comment]
@vinumweb Glad to hear that you have solved this problem. I am closing this, feel free to reopen if you have any further questions.
