### ISSUE TITLE
bug: Unable to seed database on neon

### ISSUE THREAD

**Issue by lewmilburn** [logto-io/logto#5821]
### Describe the bug
```
2024-05-04 19:38:26 
2024-05-04 19:38:26 > cli
2024-05-04 19:38:26 > logto db seed --swe
2024-05-04 19:38:26 
2024-05-04 19:38:29 - Create tables
2024-05-04 19:38:31 info ✔ Create tables
2024-05-04 19:38:31 info ✔ [default] Generated config oidc.privateKeys
2024-05-04 19:38:32 info ✔ [default] Generated config oidc.cookieKeys
2024-05-04 19:38:32 info ✔ [default] Seed OIDC config
2024-05-04 19:38:32 info ✔ [admin] Generated config oidc.privateKeys
2024-05-04 19:38:32 info ✔ [admin] Generated config oidc.cookieKeys
2024-05-04 19:38:32 info ✔ [admin] Seed OIDC config
2024-05-04 19:38:33 info ✔ Cloud Service Application successfully created for: default
2024-05-04 19:38:34 info ✔ Created machine-to-machine applications for Management API proxy
2024-05-04 19:38:34 info ✔ Initialized tenant organization template
2024-05-04 19:38:34 info ✔ Assigned the proxy roles to the applications
2024-05-04 19:38:34 info ✔ Created tenant organizations
2024-05-04 19:38:34 info ✔ Seed data
2024-05-04 19:38:34 error error: Failed to get encrypted password: User "logto_tenant_portaldb" has no password assigned.
2024-05-04 19:38:34     at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
2024-05-04 19:38:34     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-04 19:38:34     at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:21:13)
2024-05-04 19:38:34     at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:74:16)
2024-05-04 19:38:34     at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection.js:108:18)
2024-05-04 19:38:34     at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/bindPool.js:108:20)
2024-05-04 19:38:34     at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
2024-05-04 19:38:34     at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
2024-05-04 19:38:34   length: 171,
2024-05-04 19:38:34   severity: 'ERROR',
2024-05-04 19:38:34   code: 'XX000',
2024-05-04 19:38:34   detail: undefined,
2024-05-04 19:38:34   hint: undefined,
2024-05-04 19:38:34   position: undefined,
2024-05-04 19:38:34   internalPosition: undefined,
2024-05-04 19:38:34   internalQuery: undefined,
2024-05-04 19:38:34   where: undefined,
2024-05-04 19:38:34   schema: undefined,
2024-05-04 19:38:34   table: undefined,
2024-05-04 19:38:34   column: undefined,
2024-05-04 19:38:34   dataType: undefined,
2024-05-04 19:38:34   constraint: undefined,
2024-05-04 19:38:34   file: 'control_plane_connector.c',
2024-05-04 19:38:34   line: '181',
2024-05-04 19:38:34   routine: 'ConstructDeltaMessage'
2024-05-04 19:38:34 }
2024-05-04 19:38:34 error Error ocurred during seeding your database.
2024-05-04 19:38:34 
2024-05-04 19:38:34   Nothing has changed since the seeding process was in a transaction.
2024-05-04 19:38:34   Try to fix the error and seed again.
2024-05-04 19:38:34 error: Failed to get encrypted password: User "logto_tenant_portaldb" has no password assigned.
2024-05-04 19:38:34     at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
2024-05-04 19:38:34     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-04 19:38:34     at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:21:13)
2024-05-04 19:38:34     at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:74:16)
2024-05-04 19:38:34     at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection.js:108:18)
2024-05-04 19:38:34     at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/bindPool.js:108:20)
2024-05-04 19:38:34     at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
2024-05-04 19:38:34     at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
2024-05-04 19:38:34   length: 171,
2024-05-04 19:38:34   severity: 'ERROR',
2024-05-04 19:38:34   code: 'XX000',
2024-05-04 19:38:34   detail: undefined,
2024-05-04 19:38:34   hint: undefined,
2024-05-04 19:38:34   position: undefined,
2024-05-04 19:38:34   internalPosition: undefined,
2024-05-04 19:38:34   internalQuery: undefined,
2024-05-04 19:38:34   where: undefined,
2024-05-04 19:38:34   schema: undefined,
2024-05-04 19:38:34   table: undefined,
2024-05-04 19:38:34   column: undefined,
2024-05-04 19:38:34   dataType: undefined,
2024-05-04 19:38:34   constraint: undefined,
2024-05-04 19:38:34   file: 'control_plane_connector.c',
2024-05-04 19:38:34   line: '181',
2024-05-04 19:38:34   routine: 'ConstructDeltaMessage'
2024-05-04 19:38:34 }
2024-05-04 19:38:34 
2024-05-04 19:38:34 Specify --help for available options
```

### How to reproduce?
1. logto db seed

### Context

- [ ] Logto Cloud
- [X] Self-hosted, Logto version = @logto/cli v1.15.0
  - [X] Container (Docker image)
  - [ ] Raw Node.js

**Comment by simeng-li** [comment]
<img width="670" alt="image" src="https://github.com/logto-io/logto/assets/36393111/4624260a-7af4-40e7-8ebd-97648c9bc9da"/>

Looks like your db user does not have a password set.

**Comment by Vmrbee03** [comment]
Never

**Comment by Vmrbee03** [comment]
> Never

Again if u ant serious

**Comment by darcyYe** [comment]
Have you tried seeding the DB with `logto db seed --encrypt-base-role` option?
