### ISSUE TITLE
bug: OpenAPI specification is invalid

### ISSUE THREAD

**Issue by mostafa** [logto-io/logto#6043]
### Describe the bug

When I use the `openapi-generator-cli` to generate a Go client from the API specification generated from the API at `/api/swagger.json`, I get the following validation errors and nothing is generated by the CLI:

```bash
docker run --rm \
    -v "./logto-client:/local" \
    openapitools/openapi-generator-cli generate \
    -i http://<ip-address>:3002/api/swagger.json \ # This is the IP address and port that is visible to the container
    -g go \
    --package-name logto \
    -p withGoMod=false \
    -p goImportAlias=logto \
    -o /local/
```

<details>
<summary>See validation errors</summary>

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 18, Warning count: 0
Errors:
        -components.parameters.Parameter name factoryId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name resourceId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name applicationId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name ssoConnectorId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name connectorFactoryId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name organizationScopeId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name organizationInvitationId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name connectorId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name scopeId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name logId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name roleId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name keyId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name organizationId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name verificationId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name organizationRoleId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name userId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name hookId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.parameters.Parameter name domainId:root doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
 
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

</details>

If I use the suggested fix and use the `--skip-validate-spec` flag, I still see the errors, but the code will be generated. However, the generated code is invalid and doesn't compile. I initially thought that there is a problem with the Go extension of the `openapi-generator-cli`, but then I used the [Swagger Editor](https://editor.swagger.io/) and found out that the OpenAPI spec file is actually invalid.

### Expected behavior

I'd like to see an OpenAPI specification document that complies with the OpenAPI 2/3 standards, so I can generate a client SDK from it.

### How to reproduce?

Explained above using Docker, but one can also use the Java (JAR) file ([install doc](https://github.com/OpenAPITools/openapi-generator?tab=readme-ov-file#1---installation)).

### Screenshots

![image](https://uploads.linear.app/65ddb27d-1d2f-481b-a190-1a5d402b169e/7482475d-b6d9-411f-98c2-58fdf2621837/54cd494b-4955-4137-8595-72b00abb2817?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY1ZGRiMjdkLTFkMmYtNDgxYi1hMTkwLTFhNWQ0MDJiMTY5ZS83NDgyNDc1ZC1iNmQ5LTQxMWYtOThjMi01OGZkZjI2MjE4MzcvNTRjZDQ5NGItNDk1NS00MTM3LTg1OTUtNzJiMDBhYmIyODE3IiwiaWF0IjoxNzE4NzczMTUwLCJleHAiOjMzMjg5MzMzMTUwfQ.7URQlo2_ROvy65rlp9Ax_9RY6SByCsergiNRJRq2zTQ)

**Comment by mostafa** [comment]
**Update:**

I imported the OpenAPI file into Postman. Then I exported the Postman collection (saved it as a file) and converted it back to OpenAPI using the [`postman-to-openapi`](https://joolfe.github.io/postman-to-openapi/) tool. The generated Go client from the converted OpenAPI spec doc is very messy.
