### ISSUE TITLE
bug: self host,Create application error ,how to fix?

### ISSUE THREAD

**Issue by vjeson** [logto-io/logto#6540]
latest version deploy with docker compose

error

lobe-logto     | QQcipqkyi-ec1pGH   <-- POST /api/applications
lobe-logto     | QQcipqkyi-ec1pGH error TypeError: fetch failed
lobe-logto     |     at node:internal/deps/undici/undici:13178:13
lobe-logto     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lobe-logto     |     at async function_ (file:///etc/logto/node_modules/.pnpm/ky@1.2.3/node_modules/ky/distribution/core/Ky.js:18:28)
lobe-logto     |     at async Ky._retry (file:///etc/logto/node_modules/.pnpm/ky@1.2.3/node_modules/ky/distribution/core/Ky.js:215:20)
lobe-logto     |     at async result.<computed> [as json] (file:///etc/logto/node_modules/.pnpm/ky@1.2.3/node_modules/ky/distribution/core/Ky.js:54:39)
lobe-logto     |     at async getAdminTenantTokenValidationSet (file:///etc/logto/packages/core/build/main-HJQVK3RU.js:3982:25)
lobe-logto     |     at async getKeysAndIssuer (file:///etc/logto/packages/core/build/main-HJQVK3RU.js:4031:22)
lobe-logto     |     at async verifyBearerTokenFromRequest (file:///etc/logto/packages/core/build/main-HJQVK3RU.js:4038:28)
lobe-logto     |     at async authMiddleware (file:///etc/logto/packages/core/build/main-HJQVK3RU.js:4064:48)
lobe-logto     |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:2082:5
lobe-logto     |     at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:109:16)
lobe-logto     |     at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5
lobe-logto     |     at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:52:26
lobe-logto     |     at async compressMiddleware (/etc/logto/node_modules/.pnpm/koa-compress@5.1.1/node_modules/koa-compress/lib/index.js:56:5)
lobe-logto     |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:739:7
lobe-logto     |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:1218:7 {
lobe-logto     |   headers: {
lobe-logto     |     'Access-Control-Allow-Origin': 'https://xxx.com',
lobe-logto     |     'Access-Control-Expose-Headers': '*',
lobe-logto     |     vary: 'Origin'
lobe-logto     |   },
lobe-logto     |   [cause]: AggregateError [ETIMEDOUT]:
lobe-logto     |       at internalConnectMultiple (node:net:1118:18)
lobe-logto     |       at internalConnectMultiple (node:net:1186:5)
lobe-logto     |       at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
lobe-logto     |       at listOnTimeout (node:internal/timers:583:11)
lobe-logto     |       at process.processTimers (node:internal/timers:519:7) {
lobe-logto     |     code: 'ETIMEDOUT',
lobe-logto     |     [errors]: [ [Error], [Error], [Error], [Error] ]
lobe-logto     |   }

**Comment by vjeson** [comment]
This maybe a bug in lobechat ,not logto
