### ISSUE TITLE
bug: password with space service error

### ISSUE THREAD

**Issue by puzzle9** [logto-io/logto#6582]
### Describe the bug

Password contains spaces, server error occurred during registration

### Expected behavior

Password cannot contain spaces or can be registered normally

### How to reproduce?

```bash
curl 'http://localhost:3001/api/interaction/profile' \
  -X 'PATCH' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: _logto={"appId":"demo-app"}; _interaction=BERmtVd3AZT6YSJLbPhzt; _interaction.sig=8R2x7Pl41Prk0mNEut9nn0mabQk' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:3001' \
  -H 'Referer: http://localhost:3001/register/password' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"password":"pwd have space123"}'
```

```bash
app-1  | Me4ori-KGj7UVHDx   <-- PATCH /api/interaction/profile
app-1  | Me4ori-KGj7UVHDx error TypeError: fetch failed
app-1  |     at node:internal/deps/undici/undici:13178:13
app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
app-1  |     at async PasswordPolicyChecker.hasBeenPwned (file:///etc/logto/packages/toolkit/core-kit/lib/password-policy.js:226:26)
app-1  |     at async PasswordPolicyChecker.check (file:///etc/logto/packages/toolkit/core-kit/lib/password-policy.js:97:43)
app-1  |     at async validatePassword (file:///etc/logto/packages/core/build/main-HJQVK3RU.js:15650:18)
app-1  |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:15832:7
app-1  |     at async guardMiddleware (file:///etc/logto/packages/core/build/main-HJQVK3RU.js:4242:7)
app-1  |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:2051:7
app-1  |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:2082:5
app-1  |     at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:64:16)
app-1  |     at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5
app-1  |     at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:52:26
app-1  |     at async compressMiddleware (/etc/logto/node_modules/.pnpm/koa-compress@5.1.1/node_modules/koa-compress/lib/index.js:56:5)
app-1  |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:739:7
app-1  |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:1218:7
app-1  |     at async file:///etc/logto/packages/core/build/main-HJQVK3RU.js:1067:7 {
app-1  |   [cause]: AggregateError [ETIMEDOUT]:
app-1  |       at internalConnectMultiple (node:net:1118:18)
app-1  |       at internalConnectMultiple (node:net:1186:5)
app-1  |       at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
app-1  |       at listOnTimeout (node:internal/timers:583:11)
app-1  |       at process.processTimers (node:internal/timers:519:7) {
app-1  |     code: 'ETIMEDOUT',
app-1  |     [errors]: [ [Error], [Error], [Error], [Error] ]
app-1  |   }
app-1  | }
app-1  | Me4ori-KGj7UVHDx   --> PATCH /api/interaction/profile 500 540ms 36b
```

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.19 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

![image](https://github.com/user-attachments/assets/42e43edc-6dc5-4a63-b580-a6bf78caf6a8)

**Comment by charIeszhao** [comment]
From the error, it seems your server does not have access to the `https://api.pwnedpasswords.com`, which is the online service we used to check if your input password has been breached.

So you can check your firewall config on your server, or turn off the check in "password policy".

<img width="412" alt="image" src="https://github.com/user-attachments/assets/bbca9884-bb9d-4320-9f56-95328409574d">
